[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
random_number_gen = "BuTi7S9im4n85wxH5LixDNxcp13ywzM2jTPmfVRVdN9q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jayyy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
